### ISSUE TITLE
`vagrant ssh -c` does not work

### ISSUE THREAD

**Issue by tknerr** [tknerr/vagrant-managed-servers#66]
With version 0.8.0.dev and vagrant 1.8.5 I get this:

```
Y:\repo\tmp\managed-servers>vagrant ssh -c "ls -la /vagrant" managed_linux
==> managed_linux: The machine is backed by a cloud provider (managed), caching
==> managed_linux: will be disabled.
Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.5.9/lib/childprocess/windows/process_builder.rb:87:in `create_process': The system cannot find the file specified. (2) (ChildProcess::LaunchError)
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.5.9/lib/childprocess/windows/process_builder.rb:34:in `start'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.5.9/lib/childprocess/windows/process.rb:69:in `launch_process'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/ssh.rb:187:in `exec'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/ssh_run.rb:53:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/home/.vagrant.d/gems/gems/vagrant-managed-servers-0.8.0.dev/lib/vagrant-managed-servers/action/warn_networks.rb:14:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:225:in `action_raw'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:200:in `block in action'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:182:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:182:in `block in action'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `call'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `action'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/ssh/command.rb:49:in `block in execute'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `each'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/ssh/command.rb:41:in `execute'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
        from Y:/tools/vagrant/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'
```

**Comment by tknerr** [comment]
Not an issue with vagrant-managed-servers. Same thing happens with any other provider in my environment...
